config/routes.rb
Rails.application.routes.draw do
  resources :statuses

end

app/models/status.rb
class Status < ActiveRecord::Base

  # user_id毎の最新レコード
  scope :latest_by_user, -> {
    sub_query = <<-SQL
      SELECT user_id,
        MAX(CASE WHEN logged_out_at IS NULL THEN logged_in_at ELSE logged_out_at END) AS max_datetime
      FROM statuses
      GROUP BY user_id
    SQL

    join_sql = <<-SQL
      INNER JOIN (#{sub_query}) AS sub
        ON sub.user_id = statuses.user_id
        AND sub.max_datetime = CASE WHEN statuses.logged_out_at IS NULL THEN statuses.logged_in_at ELSE statuses.logged_out_at END
    SQL

    joins(join_sql)
  }

  # 入室中なら真。さもなくば偽。
  def inside?
    logged_out_at.nil?
  end

  # 滞在時間
  def length_of_stay
    end_at = try(:logged_out_at) || Time.current
    end_at - logged_in_at
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.latest_by_user
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  def create
    if params[:status][:toggle] == '1'
      @status = Status.new(status_params)
      @status.logged_in_at = Time.current
      @status.save
    else
      @status = Status.where(user_id: status_params[:user_id]).last
      # login記録がないがlogoutしようとした場合は何もしない
      if @status && @status.logged_out_at.nil?
        @status.logged_out_at = Time.current
        @status.save
      end
    end
    render json: { status: "ok" }
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Olno</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="../bower_components/html5shiv/dist/html5shiv.js"></script>
  <script src="../bower_components/respond/dest/respond.min.js"></script>
  <![endif]-->
</head>
<body>
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <a href="../" class="navbar-brand">Olno</a>
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar-main">
      <ul class="nav navbar-nav">
        <!--<li class="dropdown">-->
          <!--<a class="dropdown-toggle" data-toggle="dropdown" href="#" id="themes">Themes <span class="caret"></span></a>-->
          <!--<ul class="dropdown-menu" aria-labelledby="themes">-->
            <!--<li><a href="../default/">Default</a></li>-->
            <!--<li class="divider"></li>-->
            <!--<li><a href="../cerulean/">Cerulean</a></li>-->
            <!--<li><a href="../cosmo/">Cosmo</a></li>-->
            <!--<li><a href="../cyborg/">Cyborg</a></li>-->
            <!--<li><a href="../darkly/">Darkly</a></li>-->
            <!--<li><a href="../flatly/">Flatly</a></li>-->
            <!--<li><a href="../journal/">Journal</a></li>-->
            <!--<li><a href="../lumen/">Lumen</a></li>-->
            <!--<li><a href="../paper/">Paper</a></li>-->
            <!--<li><a href="../readable/">Readable</a></li>-->
            <!--<li><a href="../sandstone/">Sandstone</a></li>-->
            <!--<li><a href="../simplex/">Simplex</a></li>-->
            <!--<li><a href="../slate/">Slate</a></li>-->
            <!--<li><a href="../spacelab/">Spacelab</a></li>-->
            <!--<li><a href="../superhero/">Superhero</a></li>-->
            <!--<li><a href="../united/">United</a></li>-->
            <!--<li><a href="../yeti/">Yeti</a></li>-->
          <!--</ul>-->
        <!--</li>-->
        <!--<li>-->
          <!--<a href="../help/">Help</a>-->
        <!--</li>-->
        <!--<li class="dropdown">-->
          <!--<a class="dropdown-toggle" data-toggle="dropdown" href="#" id="download">Flatly <span class="caret"></span></a>-->
          <!--<ul class="dropdown-menu" aria-labelledby="download">-->
            <!--<li><a href="http://jsfiddle.net/bootswatch/jmg3gykg/">Open Sandbox</a></li>-->
            <!--<li class="divider"></li>-->
            <!--<li><a href="./bootstrap.min.css">bootstrap.min.css</a></li>-->
            <!--<li><a href="./bootstrap.css">bootstrap.css</a></li>-->
            <!--<li class="divider"></li>-->
            <!--<li><a href="./variables.less">variables.less</a></li>-->
            <!--<li><a href="./bootswatch.less">bootswatch.less</a></li>-->
            <!--<li class="divider"></li>-->
            <!--<li><a href="./_variables.scss">_variables.scss</a></li>-->
            <!--<li><a href="./_bootswatch.scss">_bootswatch.scss</a></li>-->
          <!--</ul>-->
        <!--</li>-->
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <!--<li><a href="http://builtwithbootstrap.com/" target="_blank">Built With Bootstrap</a></li>-->
        <!--<li><a href="https://wrapbootstrap.com/?ref=bsw" target="_blank">WrapBootstrap</a></li>-->
      </ul>

    </div>
  </div>
</div>

<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == "notice" ? "success" : "error" %>">
    <%= msg %>
  </div>
<% end %>

<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/statuses/_form.html.erb
<%= form_for(@status) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :logged_in_at %><br>
    <%= f.datetime_select :logged_in_at %>
  </div>
  <div class="field">
    <%= f.label :logged_out_at %><br>
    <%= f.datetime_select :logged_out_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing Status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<h1>Listing Statuses</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Logged in at</th>
      <th>Logged out at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @statuses.each do |status| %>
      <tr>
        <td><%= status.user_id %></td>
        <td><%= status.logged_in_at %></td>
        <td><%= status.logged_out_at %></td>
        <td><%= link_to 'Show', status %></td>
        <td><%= link_to 'Edit', edit_status_path(status) %></td>
        <td><%= link_to 'Destroy', status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Status', new_status_path %>

app/views/statuses/new.html.erb
<h1>New Status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p>
  <strong>User:</strong>
  <%= @status.user_id %>
</p>

<p>
  <strong>Logged in at:</strong>
  <%= @status.logged_in_at %>
</p>

<p>
  <strong>Logged out at:</strong>
  <%= @status.logged_out_at %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>